spring.application.name=planmytrip

spring.datasource.url=jdbc:mysql://localhost:3306/planmytrip
spring.datasource.username=root
spring.datasource.password=2424

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# SMTP configuration (example: Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=appukumar1204@gmail.com
spring.mail.password=wdmqgoujgszfdfma
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true